<?php

namespace SistemaBundle\Repository;

/**
 * CategoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * Cat controller.
 *
 * @Route("cat")
 */ 
class CategoriasRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * Lists all cat entities.
     *
     * @Route("/", name="cat_index")
     * @Method("GET")
     */
    public function findOneByIdJoinedToCategory($produtosId) 
    {
        $query = $this->getEntityManager()
                        ->createQuery(
           'SELECT p, c FROM SistemaBundle:Produtos p
            JOIN p.categorias c
            WHERE p.id = :id'
                        )->setParameter('id', $produtosId);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
        
    }

}


